title: Isaac Ren
description: Personal webpage
domain: isaacxren.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://isaacxren.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: Isaac Ren
twitter:
  username: isaac_paperclip
github:
  username: th-rtyf-re

theme: null

# Build settings
plugins:
  - jekyll-seo-tag

sass:
  style: compressed